services:
  kinotower-postgres:
    image: postgres:18.3-alpine
    container_name: kinotower-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kinotower
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5467:5432"
    volumes:
      - ./postgres-data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kinotower"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  kinotower-postgres-migrate:
    image: migrate/migrate:v4.19.1
    container_name: kinotower-postgres-migrate
    depends_on:
      kinotower-postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations

networks:
  default:
    name: kinotower-network